pipeline {
    agent any
    
    tools {
        nodejs 'Node_22_13'
        'hudson.plugins.sonar.SonarRunnerInstallation' 'SonarScanner'
    }
    
    stages {
        stage('Install and Test') {
            steps {
                dir('backend') {
                    sh 'npm install'
                    sh 'npm run test:cov -- --maxWorkers=1'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('backend') {
                    script {
                        def snHome = tool name: 'SonarScanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                        
                        withSonarQubeEnv('SonarServer') { 
                        sh "${snHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time: 8, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}