pipeline {
    agent any
    
    tools {
        nodejs 'Node_22_13'
        'hudson.plugins.sonar.SonarRunnerInstallation' 'SonarScanner'
    }
    
    stages {
        stage('Install and Test') {
            steps {
                dir('backend') {
                    sh 'npm install'
                    sh 'npm run test:cov -- --maxWorkers=1'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('backend') {
                    script {
                        def snHome = tool name: 'SonarScanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                        
                        sh "grep -E '^SF:.*src/|^DA:|^BR:|^LH:|^LF:|^end_of_record' coverage/lcov.info > coverage/lcov_cleaned.info"
                        sh "sed -i 's|SF:.*src/|SF:src/|g' coverage/lcov_cleaned.info"

                        withSonarQubeEnv('SonarServer') { 
                        sh "${snHome}/bin/sonar-scanner -Dsonar.javascript.node.maxspace=512 -Dsonar.javascript.lcov.reportPaths=coverage/lcov_cleaned.info -Dsonar.scm.disabled=true"
                        }
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                dir('backend') {
                    timeout(time: 5, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }
    }
}