pipeline {
    agent any

    tools {
        nodejs 'Node_22_13'
        'hudson.plugins.sonar.SonarRunnerInstallation' 'SonarScanner'
    }

    stages {
        stage('Install and Test') {
            steps {
                dir('frontend-angular') {
                    sh 'npm install'
                    sh 'npm run ng test --no-watch --code-coverage --browsers=ChromeHeadless'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('frontend-angular') {    
                    withSonarQubeEnv('SonarQubeServer') {
                        sh 'sonar-scanner'
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                dir('frontend-angular') {
                    timeout(time:5, unit:'MINUTES') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }
    }
}