pipeline {
    agent any

    tools {
        nodejs 'Node_22_13'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install and Test') {
            steps {
                dir('frontend-angular') {
                    sh 'npm install'
                    sh 'ng test --no-watch --code-coverage'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('frontend-angular') {    
                    withSonarQubeEnv('SonarQubeServer') {
                        sh 'sonar-scanner'
                    }
                }
            }
        }

        stage("Quality Gate") {
            steps {
                timeout(time:8, unit:'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}